server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: "jdbc:postgresql://localhost:4321/lec-budget-db"
    username: admin
    password: admin
  jpa:
    open-in-view: false
  main:
    banner-mode: off
  security:
    oauth2:

